version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - C:/Program Files/Redis/redis.windows.conf:/usr/local/etc/redis/redis.conf